# Generated by Django 5.0.6 on 2024-06-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_products_numreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ameer1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
