# Generated by Django 5.0.6 on 2024-06-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_products_ameer1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ameer1',
        ),
    ]
